#!/data/data/com.termux/files/usr/bin/bash

pkill -f com.termux.x11

### General env vars

export WINEESYNC=1
##export MESA_VK_WSI_PRESENT_MODE=mailbox
export MESA_VK_WSI_PRESENT_MODE=fifo_relaxed
export MANGOHUD=1
export MANGOHUD_DLSYM=1
export MANGOHUD_CONFIGFILE=~/.config/MangoHud/MangoHud.conf
export DXVK_HUD=
export DXVK_CONFIG_FILE="$HOME/dxvk.conf"
### Enable it if you have Freedreno driver installed

##export MESA_LOADER_DRIVER_OVERRIDE=kgsl
##export GALLIUM_DRIVER=freedreno

### General settings

##export vblank_mode=0
export DXVK_CONFIG_FILE="$HOME/dxvk.conf"
export DXVK_ASYNC=1
export VKD3D_FEATURE_LEVEL=12_0
export VKD3D_SHADER_MODEL=6_6
export WINE_DISABLE_FULLSCREEN_HACK=0
export WINE_LOGICAL_CPUS_AS_CORES=8
export WINE_CPU_TOPOLOGY=8:3,4,5,6,7

### Wrapper specific settings

export ADRENOTOOLS_DRIVER_NAME="vulkan.adreno.so"
export ADRENOTOOLS_DRIVER_PATH="$PREFIX/drivers/"
export ADRENOTOOLS_HOOKS_PATH="$PREFIX/lib"
export VK_ICD_FILENAMES=$PREFIX/share/vulkan/icd.d/wrapper_icd.aarch64.json

### Debugging env vars

export WINEDEBUG=-all
#export VK_LAYER_PATH="$PREFIX/share/vulkan/explicit_layers.d"
#export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump
#export DXVK_LOG_LEVEL=debug
#export DXVK_LOG_PATH=/sdcard/dxvk
#export VK_VALIDATION_LAYER_DEBUG=all
#export MESA_VK_WSI_DEBUG=sw

### Unsupported env vars (limitations of Android). DO NOT ENABLE IT!

export WINEFSYNC=0

###
su -c setenforce 0
sudo chown -R u0_a453:input /dev/input/event11 
su -c ulimit -n 827680
clear


        echo "Launching Proton-ARM64EC"
	TERMUX_X11_FORCE_FLIP=1 termux-x11 :1 & 
	sleep 1 
	am start --user 0 -n com.termux.x11/.MainActivity 
        sleep 1 
        DISPLAY=:1 \
        WINE_DISABLE_KERNEL_WRITEWATCH=1 \
	WINEPREFIX=~/wineprefix/winefaudio ~/winetricks -q faudio
